SFC-259 save roles and users
Salesfactory/gpt-rag-frontend pull request #57
Opened 2024-06-20 22:37 UTC by PedroLabrador

2024-06-21 15:15 UTC, maacaro requested changes
@PedroLabrador need work!

2024-06-21 15:15 UTC, maacaro commented on backend/app.py
> +        keySecretName = 'orchestrator-host--checkuser'
@PedroLabrador estono deberia ser una varaiable de entorno o semejante?

2024-06-21 15:15 UTC, maacaro commented on backend/app.py
> +        keySecretName = 'orchestrator-host--checkuser'
@PedroLabrador  same here

2024-06-21 17:12 UTC, Alexjes98 commented on backend/app.py
> +        keySecretName = 'orchestrator-host--checkuser'
Ummm pues entonces deberíamos cambiar todos los endpoints porque todos tienen esta forma, aunque no estoy seguro que sea tan necesario guardarlo en una variable de entorno

2024-06-24 16:01 UTC, Alexjes98 approved these changes

2024-06-24 16:01 UTC, merged